---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "https://diracdeltas.github.io/blog"
title: "discrete blogarithm"
canonifyurls: true
theme: "Lanyon"
...
