---
contentdir: "content"
layoutdir: "layouts"
indexes:
  category: "categories"
publishdir: "public"
baseurl: "https://diracdeltas.github.io/blog"
title: "discrete blogarithm"
theme: "Lanyon"
canonifyurls: true
...
