---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
baseurl: "https://blog.azuki.vip/"
title: "discrete blogarithm"
theme:
  - Lanyon
  - my-shortcodes
canonifyurls: true
markup:
    goldmark:
          renderer:
                  unsafe: true
params:
  title:
    discrete blogarithm
  description:
    "yan's blog"
